# Generated by Django 3.1.7 on 2021-07-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='upload')),
                ('upload_x_hdr', models.FileField(blank=True, upload_to='')),
                ('upload_x_img', models.FileField(blank=True, upload_to='')),
                ('upload_y_hdr', models.FileField(blank=True, upload_to='')),
                ('upload_y_img', models.FileField(blank=True, upload_to='')),
                ('upload_z_hdr', models.FileField(blank=True, upload_to='')),
                ('upload_z_img', models.FileField(blank=True, upload_to='')),
                ('result_hdr', models.FileField(blank=True, upload_to='')),
                ('result_img', models.FileField(blank=True, upload_to='')),
                ('result_x_hdr', models.FileField(blank=True, upload_to='')),
                ('result_x_img', models.FileField(blank=True, upload_to='')),
                ('result_y_hdr', models.FileField(blank=True, upload_to='')),
                ('result_y_img', models.FileField(blank=True, upload_to='')),
                ('result_z_hdr', models.FileField(blank=True, upload_to='')),
                ('result_z_img', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': '上传的图片',
                'verbose_name_plural': '上传的图片',
                'db_table': 'upload_images',
            },
        ),
    ]
