# Generated by Django 3.1.7 on 2021-07-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain_seg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='result_x_hdr',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='result_y_hdr',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='result_z_hdr',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='upload_x_hdr',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='upload_y_hdr',
        ),
        migrations.RemoveField(
            model_name='uploadimage',
            name='upload_z_hdr',
        ),
    ]
