# Generated by Django 3.1.7 on 2021-07-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain_seg', '0002_auto_20210701_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='result_x_img',
            new_name='result_img_x',
        ),
        migrations.RenameField(
            model_name='uploadimage',
            old_name='result_y_img',
            new_name='result_img_y',
        ),
        migrations.RenameField(
            model_name='uploadimage',
            old_name='result_z_img',
            new_name='result_img_z',
        ),
        migrations.RenameField(
            model_name='uploadimage',
            old_name='upload_x_img',
            new_name='upload_img_x',
        ),
        migrations.RenameField(
            model_name='uploadimage',
            old_name='upload_y_img',
            new_name='upload_img_y',
        ),
        migrations.RenameField(
            model_name='uploadimage',
            old_name='upload_z_img',
            new_name='upload_img_z',
        ),
    ]
