# Generated by Django 3.1.7 on 2021-07-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_seg', '0003_auto_20210701_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
